### ISSUE TITLE
_tkinter.TclError: bitmap "extrafiles/images/assistant2.ico" not defined

### ISSUE THREAD

**Issue by ianni67** [roshan9419/PersonalAssistantChatbot#6]
Hello, I'm trying to run your software on my Linux machine, but I get this weird error:
`_tkinter.TclError: bitmap "extrafiles/images/assistant2.ico" not defined
`
Please, note that the file is there.
Can you, please, help me to sort out this error?

**Comment by roshan9419** [comment]
See, I have already tried to run this on Linux, but it requires a lot of change in libraries and codes to make it compatible with both Linux and Windows. This project is currently supported on Windows OS only.
In order to run this project on Linux, you have to change some codes like replacing pyttsx3 with another library and its usage code.

**Comment by ianni67** [comment]
Thank you for taking the time to answer.
You might want to add this piece of information to the readme, so people like me, who do not use windows, will not spend time trying to sort out what's wrong.
